### ISSUE TITLE
Couldn't generate transcript

### ISSUE THREAD

**Issue by mchuahua** [sarah157/ubc-latex-transcript#1]
Hi, 

Please see image below. 

![image](https://github.com/sarah157/ubc-latex-transcript/assets/43918886/e14f51c0-60af-40e2-9b57-834f1170ca8c)

I am on "Grades Summary" page (https://ssc.adm.ubc.ca/sscportal/servlets/SSCMain.jsp?function=SessGradeRpt)

**Comment by sarah157** [comment]
Hi, thanks for reaching out.

Is there anything printed out in the console? I may have experienced something similar to this before; re-clicking the "Your Grades Summary" tab helped (but reloading the page didn't).

**Comment by mchuahua** [comment]
![image](https://github.com/sarah157/ubc-latex-transcript/assets/43918886/577c0ce1-6f8f-45fc-b5f6-30aa75f2c91a)

Re-clicking the tab did not fix the issue.

**Comment by sarah157** [comment]
The error is due to calling `replace` on an undefined course title. I pushed out a quick [fix](https://github.com/sarah157/ubc-latex-transcript/commit/138048704f25694457e74f327a442f3f479cf891#diff-7510a8ff132fa776d9464f906e5e02b9688a0b104f8e7391b90053872cfad28a) until I look more into the course title situation. 

The update (v0.1.2) will probably be available tomorrow. Please let me know if you're still getting errors or if you have any feedback!

**Comment by sarah157** [comment]
Update has been published!

**Comment by mchuahua** [comment]
Thanks! It's working.

Only thing here is that some course titles and/or repeated courses don't populate correctly:

![image](https://github.com/sarah157/ubc-latex-transcript/assets/43918886/90636104-85be-4e54-833f-00e3e65d887e)
![image](https://github.com/sarah157/ubc-latex-transcript/assets/43918886/267a4c1f-ebaf-41ab-afa2-b289532a4053)

This might've had some relation to the original undefined course title error.

**Comment by mchuahua** [comment]
Also, course code is not completely correct for those that have letters:
![image](https://github.com/sarah157/ubc-latex-transcript/assets/43918886/c04bb957-17b0-480b-b8d5-2ab4cc156e86)

Should be ELEC 400M and EECE 571W

**Comment by sarah157** [comment]
Thanks for letting me know!

No idea why the first EECE 599 title is undefined. Could you try resetting the storage or uninstalling then reinstalling the extension (since course titles are cached in storage).

I'll let you know when I have an update for the course code and course title issues (will probably use the UBCGrades API for some cases).

**Comment by mchuahua** [comment]
Not a big deal and it's editable in overleaf. Great work btw and thanks for making this!

**Comment by sarah157** [comment]
Thank you!!

Edit: Course code and undefined course titles issues resolved in [v0.1.3](https://github.com/sarah157/ubc-latex-transcript/releases/tag/v0.1.3) and [v0.1.4](https://github.com/sarah157/ubc-latex-transcript/releases/tag/v0.1.4)
